stages:
  - prepare
  - lint
  - test
  - coverage

install_gems:
  stage: prepare
  script:
    - brew bundle
    - bundle install
    - bundle exec fastlane run bootstrap
  cache:
    key: straal-sdk-key-1
    paths:
      - Carthage/
    policy: pull-push
  tags:
    - ios

lint:
  stage: lint
  cache: {}
  script:
    - mkdir -p ./outputs
    - swiftlint lint --config .swiftlint_ci.yml > outputs/lint.html
  tags:
    - ios
  artifacts:
    when: always
    expire_in: 4 weeks
    paths:
      - outputs/lint.html

test:unit:
  stage: test
  dependencies: []
  cache:
    key: straal-sdk-key-1
    paths:
      - Carthage/
    policy: pull
  script:
    - bundle exec fastlane test
  artifacts:
    expire_in: 2 days
    paths:
      - DerivedData/Logs/Test
  tags:
    - ios

coverage:
  stage: coverage
  dependencies:
    - test:unit
  cache: {}
  when: always
  script:
    - bundle exec fastlane coverage
    - bundle exec danger
  tags:
    - ios
