stages:
  - prepare
  - lint
  - test
  - test_api

cache:
  paths:
    - Carthage/

install_gems:
  stage: prepare
  script:
    - bundle install
  tags:
    - ios

install_pods:
  stage: prepare
  script:
    - carthage bootstrap --no-use-binaries --platform iOS --cache-builds
  tags:
    - ios

lint:
  stage: lint
  script:
    - mkdir -p ./outputs
    - swiftlint lint --config .swiftlint_ci.yml > outputs/lint.html
  tags:
    - ios
  artifacts:
    when: always
    expire_in: 4 weeks
    paths:
      - outputs/lint.html

test:
  stage: test
  artifacts:
    when: always
    expire_in: 10 weeks
    paths:
      - outputs/report.html
  script:
    - mkdir -p outputs
    - xcodebuild test -workspace Straal.xcworkspace -scheme Straal -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 11' -sdk iphonesimulator | bundle exec xcpretty -c --report html --output outputs/report.html && exit ${PIPESTATUS[0]}

trigger_build:
  stage: test_api
  script:
    - "curl -X POST -F token=$TESTS_TRIGGER_TOKEN -F ref=$TESTS_REF -F variables[commit_hash]=$CI_COMMIT_SHA $TESTS_URL"
