stages:
  - lint
  - test

lint:
  stage: lint
  cache: {}
  script:
    - mkdir -p ./outputs
    - swiftlint lint --config .swiftlint_ci.yml > outputs/lint.html
  tags:
    - swiftlint
  artifacts:
    when: always
    expire_in: 4 weeks
    paths:
      - outputs/lint.html

test:unit:
  stage: test
  dependencies: []
  before_script:
    - bundle
  script:
    - bundle exec fastlane test
    - bundle exec fastlane coverage
    - bundle exec danger
  tags:
    - xcode.12.3
