stages:
  - prepare
  - lint
  - test
  - coverage

.xcode:
  before_script:
    - bundle install
  tags:
    - xcode

.getcarthage:
  cache:
    key: straal-sdk-key-1
    paths:
      - Carthage/
    policy: pull

prepare:
  extends: .xcode
  stage: prepare
  script:
    - bundle exec fastlane run bootstrap
  cache:
    key: straal-sdk-key-1
    paths:
      - Carthage/
    policy: pull-push

lint:
  stage: lint
  cache: {}
  script:
    - mkdir -p ./outputs
    - swiftlint lint --config .swiftlint_ci.yml > outputs/lint.html
  tags:
    - swiftlint
  artifacts:
    when: always
    expire_in: 4 weeks
    paths:
      - outputs/lint.html

test:unit:
  stage: test
  dependencies: []
  extends:
    - .getcarthage
    - .xcode
  script:
    - bundle exec fastlane test
    - bundle exec fastlane coverage
    - bundle exec danger
