excluded:
  - Carthage

opt_in_rules:
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - contains_over_first_not_nil
  - empty_enum_arguments
  - empty_parameters
  - explicit_init
  - fatal_error_message
  - first_where
  - for_where
  - joined_default_parameter
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - protocol_property_accessors_order
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - sorted_first_last
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

quick_discouraged_focused_test: warn
quick_discouraged_pending_test: error

disabled_rules:
  - line_length

identifier_name:
  excluded:
    - id

reporter: xcode
