language: swift
osx_image: xcode12.3

env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

before_install:
  - gem install bundler
  - brew bundle
  - bundle install

script:
  - swiftlint lint --config .swiftlint_travis.yml
  - bundle exec fastlane test
