language: swift
osx_image: xcode9.1

env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

before_install:
  - bundle
  - gem install xcpretty -N
  - bundle exec pod repo update
  - bundle exec pod install

script:
  - set -o pipefail
  - xcodebuild build test -workspace Straal.xcworkspace -scheme Straal -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 8' -sdk iphonesimulator | xcpretty -c
  - ./Pods/SwiftLint/swiftlint lint --config .swiftlint_travis.yml
