language: swift
osx_image: xcode13.1

env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

before_install:
  - brew bundle
  - bundle install
  - bundle exec fastlane run bootstrap

script:
  - swiftlint lint --config .swiftlint_travis.yml
  - bundle exec fastlane test
  - xcodebuild build test -workspace Straal.xcworkspace -scheme Straal -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 8' -sdk iphonesimulator | xcpretty -c
